### ISSUE TITLE
Android build fail by PGB

### ISSUE THREAD

**Issue by bau720123** [fastrde/phonegap-checkGPS#1]
I am using PGB 3.7 (build.phonegap.com)
but it will build fail in Android (ios build success...)

```
Error - Plugin error (you probably need to remove plugin files from your app): Error during processing of action! Attempting to revert... Failed to install 'de.fastr.phonegap.plugins.CheckGPS':Error: Uh oh! "/tmp/gimlet/1514/792b1384-65ab-11e3-8519-22000a98b3d6/www_android/project/cordova/plugins/de.fastr.phonegap.plugins.CheckGPS/src/android/CheckGPS.java" not found! at Object.module.exports.common.copyFile (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/platforms/common.js:43:40) at Object.module.exports.common.copyNewFile (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/platforms/common.js:72:16) at module.exports.source-file.install (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/platforms/android.js:51:20) at Object.ActionStack.process (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/util/action-stack.js:70:25) at handleInstall (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/install.js:567:20) at /home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/install.js:322:20 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:798:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:827:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:760:13) at /home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:526:49 Uh oh! "/tmp/gimlet/1514/792b1384-65ab-11e3-8519-22000a98b3d6/www_android/project/cordova/plugins/de.fastr.phonegap.plugins.CheckGPS/src/android/CheckGPS.java" not found!
```

**Comment by fastrde** [comment]
please test version 0.9.8 and let me know if it now works for both platforms.

**Comment by bau720123** [comment]
hi @fastrde 
build all success
thanks~
